#!/usr/bin/env bash

pull (){
	# $1 - package name
	mkdir $1
	adb pull /data/app/$1/base.apk $1/app.apk
}

backsmali (){
	# $1 - apk path
	echo "Apk to smali"
	apktool d $1 > /dev/null
}

build (){
	# $1 - source folder to build
	# $2 - output apk name
	echo "Smali to apk"
	apktool b $1 -o $2 > /dev/null
}

sign (){
	# $1 - apk path
	keystore=".debug.keystore"

	if [ -f "$keysotre" ]
	then
		echo "found key"
	else
		echo "creating new key"
		keytool -genkeypair -keyalg RSA -alias androiddebugkey -keypass android -keystore $keystore -storepass android -dname "CN=Android Debug,O=Android,C=US" -validity 9999
	fi

	jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -storepass android -keystore $keystore $1 androiddebugkey
}

install (){
	# $1 - apk to install
	adb install $1
}

echo "Hello World"
backsmali ~/Desktop/Labs/Android-InsecureBankv2/InsecureBankv2.apk
build ~/Desktop/InsecureBankv2 app.apk
sign app.apk
echo "Done"
