#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if source $DIR/main.sh 2> /dev/null
then
	echo "ok"
else
	DIR="$(dirname "$(readlink -f "$0")")"
	source $DIR/main.sh
fi

echo "dir: $DIR"
echo "using package: $1"
package=$1

# read -p "enter package name:" package

PS3='Please enter your choice: '
options=("set-package" "pull" "backsmali" "build" "install" "exit")
select opt in "${options[@]}"
do
	case $opt in
		"set-package")
			read -p "enter package name:" package
			;;
		"pull")
			echo "pulling package $package"
			pull $package
			;;
		"backsmali")
			echo "backsmalling $package"
			apk="$package.apk"
			smali_folder="smali-$package"
			source_folder="source-$package"
			
			backsmali $apk $smali_folder $source_folder	
			;;
		"build")
			echo "building $package"
			smali_folder="smali-$package"
			source_folder="source-$package"
			apk="mod-$package.apk"
			create_apk $source_folder $smali_folder $apk
			;;
		"install")
			echo "installing $package"
			if [ -f "mod-$package.apk" ]
			then
				echo "installing moded apk"
				install "mod-$package.apk"

			else
				echo " trying to install plain apk"
				install "$package.apk"
			fi
			;;
		"exit")
			break
			;;
		*) echo "invalid option";;
	esac
done
